server:
  port: 8085

cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: AKIARGQCQOPJ2IPVPQFW
      secret-key: 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
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/082683392979/springBoot-sqs-queue